### ISSUE TITLE
Switch to mac-fuse org?

### ISSUE THREAD

**Issue by yurikoles** [gromgit/homebrew-fuse#10]
Hi @gromgit,

Thanks for such a great tap!

I saw that there was not many formulas some time ago, so I created [mac-fuse/homebrew-fuse](https://github.com/mac-fuse/homebrew-fuse) repo based on your tap, where I semi-automatically added most of the disabled formulas, sorry for missing credits. Now I see a lot of activity in this repo, so I want to offer you to switch this repo to `mac-fuse` org umbrella. I had invited you to it as owner. I'm unsure if this possible, but I would love to drop my privileges if you want.

**Comment by lain0** [comment]
Mb it needs some docs how to migrate from fuse to mac-fuse ? 
like ```brew uninstall sshfs fuse``` ?

**Comment by gromgit** [comment]
@yurikoles Sorry for the long delay, and thanks much for the offer, but I'll decline for now.

@lain0 I've incorporated your suggestion into the [README](https://github.com/gromgit/homebrew-fuse/blob/main/README.md). Please file a new issue if it's still not clear. Thanks much!
