### ISSUE TITLE
Could dislocker be added to the formulae?

### ISSUE THREAD

**Issue by philstopford** [gromgit/homebrew-fuse#12]
It looks like brew won't install this as fuse is required, but unavailable.

**Comment by gromgit** [comment]
Dislocker has been available from the start; the formula is just called `dislocker-mac`. Read the [tap README](https://github.com/gromgit/homebrew-fuse#readme) to understand why.

Also note that there aren't any M1 bottles, because I don't have an M1 Mac (yet).

**Comment by philstopford** [comment]
Oh, wonderful. I nosed around and could not see it. It does indeed work well. Thank you!
