### ISSUE TITLE
How to install gcsfuse-mac but with a modified go.mod?

### ISSUE THREAD

**Issue by grisaitis** [gromgit/homebrew-fuse#22]
Hi! I'd like to install `gcsfuse-mac` but with a `replace` statement in the `go.mod`. also i might want to fast forward the repo to a more recent commit. 

How do I do this?

### background
Currently I have...

```
brew install macfuse
brew install gromgit/fuse/gcsfuse-mac
```

but i'm encountering a bug (https://github.com/GoogleCloudPlatform/gcsfuse/issues/548) that is easily fixable with a `replace` statement in `go.mod`, but id ont' know how to add that and `go build` or `brew reinstall` with that edit. 

### kernel info

```
➜  ~ sysctl kern.version

kern.version: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101
```

**Comment by gromgit** [comment]
Closing, since it seems to have been fixed upstream.
