### ISSUE TITLE
Getting 404 on brew install xmount-mac

### ISSUE THREAD

**Issue by my4n6** [gromgit/homebrew-fuse#23]
Hello Adrian,

I am getting a 404 during brew install xmount-mac, do you have any solution or alternative tap.

==> Downloading https://github.com/gromgit/homebrew-fuse/releases/download/xmount-mac-0.7.

curl: (22) The requested URL returned error: 404 
Error: xmount-mac: Failed to download resource "xmount-mac"
Download failed: https://github.com/gromgit/homebrew-fuse/releases/download/xmount-mac-0.7.6/xmount-mac-0.7.6.big_sur.bottle.1.tar.gz

Kind Regards

my4n6

**Comment by gromgit** [comment]
Apologies for the delay. Tracked the issue down to a weird bottling issue, it's fixed now. Please `brew update` and try your install again.

**Comment by my4n6** [comment]
Thx, Adrian. Now it is working like a charm :-)
