### ISSUE TITLE
Missing formula: sshfs

### ISSUE THREAD

**Issue by Guillawme** [gromgit/homebrew-fuse#3]
Hello,

Since the README invites us to report missing formulae, here's one: https://formulae.brew.sh/formula/sshfs

`sshfs` that stopped being updated in homebrew-core because it depends on `osxfuse` or `macfuse`, that are both distributed as casks but have an incompatible license to be dependencies of formulae in homebrew-core. But it's very useful, and it would be great to still get updates for it.

I also wonder whether it would be possible to compile `libfuse` for macOS: https://formulae.brew.sh/formula/libfuse
This one has a license compatible with distribution in homebrew-core, so if it could be compiled for macOS and dependency of `sshfs` changed to this one instead of the casks with incompatible licenses, then maybe `sshfs` could be back in homebrew-core? Problems are that 1) I have no idea how to try to do this myself (don't know Ruby, don't know how the internals of homebrew work) otherwise I would try to do it, and 2) I don't know if the homebrew maintainers would take this contribution (they seem very prompt to simply drop formulae, not sure if they can be easily convinced to reintegrate one).

Good luck with maintaining these formulae, and thank you!

**Comment by gromgit** [comment]
I started work on the necessary infrastructure to support macOS FUSE formulae, back when it was announced that all such formulae would be deprecated. Pretty much everything needed is in place, and now that all such formulae have been disabled in core, I'll begin migrating them into my own FUSE tap for all to use: https://github.com/gromgit/homebrew-fuse

That said, I'm just one guy who got deluged by a flood of unexpected responsibilities, so PRs to my tap are always welcome. Otherwise, leave an issue there and I'll get around to it as soon as I can.

> I also wonder whether it would be possible to compile libfuse for macOS: https://formulae.brew.sh/formula/libfuse

It might be possible, but getting it to do useful things on macOS requires kernel extensions that `libfuse` neither has nor supports. That's why [their own README](https://github.com/libfuse/libfuse#supported-platforms) states:

> ## Supported Platforms
> * Linux (fully)
> * BSD (mostly/best-effort)
> * **For OS-X, please use OSXFUSE**

**Comment by gromgit** [comment]
As for `sshfs` itself, I've confirmed that v2.10 is the last version that can be built with the latest MacFUSE, since that only supports FUSE API v2. Give it a shot and let me know if something breaks.

**Comment by rplCloud** [comment]
I installed sshfs a few hours ago. Works fine.

@gromgit: I never thought you would come up with a solution so quickly. Just great! Thanks a lot!

**Comment by Guillawme** [comment]
I just tried, but it didn't work. Here is the error I got:

```
$ brew install gromgit/fuse/sshfs
==> Tapping gromgit/fuse
Cloning into '/usr/local/Homebrew/Library/Taps/gromgit/homebrew-fuse'...
remote: Enumerating objects: 243, done.
remote: Counting objects: 100% (243/243), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 243 (delta 72), reused 230 (delta 64), pack-reused 0
Receiving objects: 100% (243/243), 48.53 KiB | 1.05 MiB/s, done.
Resolving deltas: 100% (72/72), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/afuse-mac.rb
No available formula with the name "afuse-mac".
In formula file: /usr/local/Homebrew/Library/Taps/gromgit/homebrew-fuse/Formula/afuse-mac.rb
Expected to find class AfuseMac, but only found: AfuseMacMac.
Error: Cannot tap gromgit/fuse: invalid syntax in tap!
```

I took care to uninstall `sshfs` I had from `core` before running this command, so I don't know what went wrong. I tried again after uninstallin `afuse` I had from core, thinking maybe it's best to get the dependencies from the same tap (since the error message mentioned `afuse`), but I got the same error when I retried.

**Comment by gromgit** [comment]
Sorry, I checked in some typos in a different formula. Please `brew update` and try again.

**Comment by Guillawme** [comment]
It worked perfectly this time, thank you!

And no worries regarding the old dependency, it's already better to receive minor version updates from your tap than nothing from core. Maybe a future macFUSE update will allow using branch 3 of sshfs, so at least now there's a way forward when this happens.
