### ISSUE TITLE
sshfs depends on missing library

### ISSUE THREAD

**Issue by grischard** [gromgit/homebrew-fuse#30]
```
dyld[31125]: Library not loaded: /usr/local/opt/glib/lib/libgthread-2.0.0.dylib
  Referenced from: /Users/stereo/bin/sshfs
  Reason: tried: '/usr/local/opt/glib/lib/libgthread-2.0.0.dylib' (no such file), '/usr/local/lib/libgthread-2.0.0.dylib' (no such file), '/usr/lib/libgthread-2.0.0.dylib' (no such file)
```

This is macOS 12.2 on arm64. `glib` is installed but it doesn't provide libgthread.

**Comment by gromgit** [comment]
What's the output of:
```
brew info glib
brew linkage glib
```

**Comment by gromgit** [comment]
Also, are you running Homebrew under Rosetta? Native ARM64 Homebrew installs all formulae under `/opt/homebrew`, not `/usr/local` as you currently have.

**Comment by grischard** [comment]
I'm very sorry, I've wasted your time because of an old sshfs binary I'd carried over in my `~/bin` from my x86 installation! Thank you for noticing that there was something wrong with the paths.

**Comment by gromgit** [comment]
No worries, as long as the problem's resolved.
